### ISSUE TITLE
package seaborn is missing from requirements

### ISSUE THREAD

**Issue by Teme-V** [vividfog/nordpool-predict-fi#4]
Looks a like seaborn is missing from requirements.txt 

`(venv) teme@HooPee:~/nordpool-predict-fi$ python nordpool_predict_fi.py --foreca
Traceback (most recent call last):
  File "/home/teme/nordpool-predict-fi/nordpool_predict_fi.py", line 13, in <module>
    from util.eval import eval
  File "/home/teme/nordpool-predict-fi/util/eval.py", line 4, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'`
manual installation `pip install seaborn` did fix the issue

**Comment by vividfog** [comment]
Thanks, fixed
